Toggling between ETH and USD in Send screen should show the same amounts #2243
AlphaWallet/alpha-wallet-ios pull request #2249
Opened 2020-11-03 12:05 UTC by vladyslav-iosdev

Closes #2243, #2244

2020-11-04 04:34 UTC, hboon commented
Need to use the "closes" keyword before each issue number. I have edited the comment.

2020-11-04 05:17 UTC, hboon requested changes

2020-11-04 05:17 UTC, hboon commented on AlphaWallet/UI/Views/AmountTextField.swift
> +        while string.last == "0" || string.last == "." {
Would the "." check cause a problem with locales where the decimal separator is a comma?

2020-11-04 05:17 UTC, hboon commented on AlphaWallet/UI/Views/AmountTextField.swift
> +    private var cryptoToDollarRatePrevValue: Double?
Can you comment on what this new set of properties do and help, maybe with respect to the 2 issues? These few classes are still quite fragile so I'm hoping we can make minimal changes to it.

2020-11-04 05:18 UTC, hboon commented
Also, can you help remove the references to "qoin" in this PR?

2020-11-04 09:54 UTC, vladyslav-iosdev commented
@hboon can u explain me in what format do we need to display value in text field?

```
///Formats string value for display in text field.
    private func formatValueToDisplayValue(_ value: Double?) -> String {
        guard let amount = value else {
            return String()
        }

        switch currentPair.left {
        case .cryptoCurrency:
//            return StringFormatter().currency(with: amount, and: Constants.Currency.usd)
            return amount.toString(decimal: 2).droppedTrailingZeros
        case .usd:
            //NOTE: for values that greater then 0.01 threshold we use different formatters
            if amount > 0.01 {
//                return StringFormatter().alternateAmount(value: amount).droppedTrailingZeros
                return amount.toString(decimal: Constants.etherFormatterFractionDigits).droppedTrailingZeros
            } else {
                return amount.toString(decimal: 18).droppedTrailingZeros
            }
        }
    }
```

using this `return StringFormatter().currency(with: amount, and: Constants.Currency.usd)` for formatting can transform value to string like this `123,123.123` that later can't be parsed to string, but `return amount.toString(decimal: 2).droppedTrailingZeros` always converts value to string with format like `123123.123`

2020-11-04 10:01 UTC, hboon commented
> @hboon can u explain me in what format do we need to display value in text field?

It should be in the format "1,234.56" or "1.234,56" [1] depending on the decimal separator for the locale. We don't deal with huge amounts much, but have to be careful to parse the thousands separator correctly. I *think* it's always the opposite of the decimal separator, but let's try to let the system to parse it to be sure.

[1] 2 or 4 decimals places depending on fiat or crypto

2020-11-04 10:03 UTC, hboon commented
If it's better/simpler to fix this with a bigger refactoring of how we format numbers, maybe a simple fix for #2243 is to simply memoize the left-right pair the user has last type/edited?

2020-11-09 06:54 UTC, hboon commented
@vladyslav-iosdev remember to buzz me again if this is good for review

2020-11-09 08:05 UTC, hboon approved these changes

2020-11-09 08:06 UTC, merged