Add support for .crypto (UnstoppableDomains) domain lookup #1931
AlphaWallet/alpha-wallet-ios pull request #2250
Opened 2020-11-04 11:26 UTC by vladyslav-iosdev

Closes #1931

2020-11-04 15:20 UTC, vladyslav-iosdev commented
@hboon all Trevis checks failed, 
https://travis-ci.com/github/AlphaWallet/alpha-wallet-ios/builds/198257445
there is message 

```
fatal: reference is not a tree: 944b91ba81721eb08705afcfd8d158b0cd42d771
The command "pod install --repo-update" failed and exited with 1 during .
Your build has been stopped.
``` 

Does it mean that i need to call `pod install --repo-update` before send commit?

2020-11-04 16:42 UTC, hboon commented
No. Shouldn’t matter. Does the commit hash mentioned exist?

2020-11-05 03:22 UTC, hboon requested changes
Are the Podfile changes needed for this PR? If so:

```
pod install
```

> [!] `CryptoSwift` requires CocoaPods version `>= 1.9.1`, which is not satisfied by your current version, `1.8.4`.


Do you want to submit a separate PR to get CocaoPods to 1.9.1 or above?

Also, since Podfile is updated, we need to update `Podfile.lock` too

2020-11-09 06:54 UTC, hboon commented
@vladyslav-iosdev remember to buzz me again if this is good for review

2020-11-09 07:49 UTC, hboon requested changes
Getting this when `pod install`:

> [!] Error installing TrustKeystore
> [!] Failed to download 'TrustKeystore': [!] /usr/local/bin/git -C /var/folders/x8/s575y2zs4xs6w6ysrvs97dtw0000gq/T/d20201109-81866-1w2vd74 checkout --quiet 0aae827ccfbbcb095bc17753dc75b9bb302392aa
> 
> fatal: reference is not a tree: 0aae827ccfbbcb095bc17753dc75b9bb302392aa

2020-11-09 07:57 UTC, vladyslav-iosdev commented
> Getting this when pod install:

its strange, it works for me fine.

2020-11-09 09:31 UTC, vladyslav-iosdev commented
@hboon removed cached pods, and reinstall them again, it works for me.

2020-11-09 14:15 UTC, hboon commented
@vladyslav-iosdev I tried 2 cases:

A) Install with Cocoapods 1.8.4

> [!] `CryptoSwift` requires CocoaPods version `>= 1.9.1`, which is not satisfied by your current version, `1.8.4`.

B) with Cocoapods 1.9.1

Installs, but looks like we need to check in the `podfile.lock` changes

2020-11-09 14:16 UTC, hboon requested changes
@vladyslav-iosdev I tried 2 cases:

A) Install with Cocoapods 1.8.4

> [!] `CryptoSwift` requires CocoaPods version `>= 1.9.1`, which is not satisfied by your current version, `1.8.4`.

B) with Cocoapods 1.9.1

Installs, but looks like we need to check in the `podfile.lock` changes

Can you also pushed PRs (or if pushed, buzz me there) to get the dependent pods' repos merged?

2020-11-09 14:22 UTC, vladyslav-iosdev commented
@hboon check it.

2020-11-09 14:30 UTC, hboon commented
Looks ok, I noticed you use Cocoapods `1.10.0`. If that's what you intended (and not `1.9.1`), that's fine.

Can you get the PRs for the dependencies? For the `UnstoppableDomainsResolution`, can you submit a PR to their repo and see if we can get it merged? Otherwise we'll have to fork it. Hopefully not. We can still settle the PRs for the other dependencies first.

2020-11-09 14:31 UTC, hboon commented
I realised I have forgotten to review the PR itself. Will get to it :)

2020-11-09 14:46 UTC, vladyslav-iosdev commented
> Looks ok, I noticed you use Cocoapods `1.10.0`. If that's what you intended (and not `1.9.1`), that's fine.
> 
> Can you get the PRs for the dependencies? For the `UnstoppableDomainsResolution`, can you submit a PR to their repo and see if we can get it merged? Otherwise we'll have to fork it. Hopefully not. We can still settle the PRs for the other dependencies first.

i suppose we will need to make a fork, because i updated UnstoppableDomainsResolution with downgrated dependency version.

2020-11-09 14:50 UTC, hboon commented
> > Looks ok, I noticed you use Cocoapods `1.10.0`. If that's what you intended (and not `1.9.1`), that's fine.
> > Can you get the PRs for the dependencies? For the `UnstoppableDomainsResolution`, can you submit a PR to their repo and see if we can get it merged? Otherwise we'll have to fork it. Hopefully not. We can still settle the PRs for the other dependencies first.
> 
> i suppose we will need to make a fork, because i updated UnstoppableDomainsResolution with downgrated dependency version.

I understand. I mean submit a PR to `UnstoppableDomainsResolution` GitHub repo and see if they can merge it in. I presume the change was just to downgrade the dependency and there's no functional change.

2020-11-09 14:54 UTC, vladyslav-iosdev commented
i am not sure if it ok for PR, i setted dependency for own forked repo for 
https://github.com/vladyslav-iosdev/EthereumABI.git (it sets CryptoSwift version to 0.10.0)
` s.dependency 'CryptoSwift', '~> 0.10.0'`

2020-11-09 14:55 UTC, vladyslav-iosdev commented
i will try to skip these changes (above)

2020-11-09 19:48 UTC, merenkoff reviewed
Please read our documentation.

2020-11-09 19:48 UTC, merenkoff commented on AlphaWallet/Core/DomainResolver.swift
> +                resolution.owner(domain: input) { result in
you need to check not owner. you need check address of ETH wallet. 

```swift 

resolution.addr(domain: "brad.crypto", ticker: "eth") { result in
  switch result {
  case .success(let returnValue):
    // 0x8aaD44321A86b170879d7A244c1e8d360c99DdA8
    let ethAddress = returnValue
  case .failure(let error):
    print("Expected eth Address, but got \(error)")
  }
}

```

2020-11-09 19:55 UTC, merenkoff requested changes
Docs https://github.com/unstoppabledomains/resolution-swift#common-examples

2020-11-16 09:13 UTC, vladyslav-iosdev commented
@hboon can u review this issue?

2020-11-17 05:30 UTC, hboon requested changes
- [ ] I had to change the commit (because the Podfile.lock seems outdated), to finish `pod install`:

```
pod 'UnstoppableDomainsResolution', :git=>'https://github.com/vladyslav-iosdev/resolution-swift.git', :commit=>'9e1283c8deede5ad936e9c355dc92f40d62d54b0'
```

- [ ] Are some of the changes like for `web3swift` and `TrustKeystore` (maybe `CryptoSwift` too?)in `Podfile` because you are mixing in changes required to get the project to build with Xcode12? They don't seem necessary? Can we exclude them

- [ ] Can you create a pull request for the UnstoppableDomainsResolution pod and try to get it merged in? We can still merge this PR with a fork first if the PR hasn't/isn't merge yet. We can update again when that's done

- [x] It doesn't seem to work when I enter "hweeboon.eth"

2020-11-17 08:25 UTC, vladyslav-iosdev commented
> * It doesn't seem to work when I enter "hweeboon.eth"

@hboon I updated resolving ens with `GetENSAddressCoordinator` if `UnstoppableDomainsResolution` get failed

2020-11-17 08:29 UTC, vladyslav-iosdev commented
> * Are some of the changes like for `web3swift` and `TrustKeystore` (maybe `CryptoSwift` too?)in `Podfile` because you are mixing in changes required to get the project to build with Xcode12? They don't seem necessary? Can we exclude them

yep we can, in case if this PR will be merged after #2143

2020-11-17 08:30 UTC, vladyslav-iosdev commented
> * [ ]  Can you create a pull request for the UnstoppableDomainsResolution pod and try to get it merged in? We can still merge this PR with a fork first if the PR hasn't/isn't merge yet. We can update again when that's done

i created PR.

2020-11-17 08:33 UTC, hboon commented
> yep we can, in case if this PR will be merged after #2143

Hmm.. ok, let's get #2143 done first. Buzz me if I'm blocking there.

2020-11-18 13:22 UTC, merenkoff approved these changes
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  UnstoppableDomainsResolution (0.1.6) successfully published
 📅  November 18th, 15:18
 🌎  https://cocoapods.org/pods/UnstoppableDomainsResolution
 👍  Tell your friends!
--------------------------------------------------------------------------------

Please use pod (0.1.6)

2020-11-18 15:25 UTC, vladyslav-iosdev commented
@hboon PR is ready for review.

2020-11-19 05:10 UTC, hboon commented
> 🎉 Congrats
> 
> ## 🚀 UnstoppableDomainsResolution (0.1.6) successfully published
> 📅 November 18th, 15:18
> 🌎 https://cocoapods.org/pods/UnstoppableDomainsResolution
> 👍 Tell your friends!
> Please use pod (0.1.6)

Thanks for the support! @merenkoff

2020-11-19 05:43 UTC, hboon commented
Forced pushed after:

* moved the network name as an `RPCServer` extension along with a comment into `DomainResolver`
* rebased master

2020-11-19 05:43 UTC, hboon approved these changes

2020-11-19 05:44 UTC, merged