Add Open in AlphaWallet DApp Browser in iOS Activities #1100
AlphaWallet/alpha-wallet-ios pull request #2267
Opened 2020-11-11 09:59 UTC by vladyslav-iosdev

Closes #1100

2020-11-12 04:21 UTC, hboon requested changes
- [x] Remember to fix the test suite.
- [ ] It crashes when I launch the extension from Safari in Simulator for iOS 12.4

2020-11-12 13:34 UTC, vladyslav-iosdev commented
> * [ ]  It crashes when I launch the extension from Safari in Simulator for iOS 12.4

i tried to reproduce it but for me its works ok, first time i did it on real device, second time tested on simulator 12.4 version.

2020-11-13 06:06 UTC, hboon requested changes
Can you squash the 2 commits into 1?

2020-11-13 06:06 UTC, hboon commented on AlphaWalletShare/ShareViewController.swift
> +                        self.storage.attachement = attachment
Do you think we can encode the URL to open directly into the custom URL, then we slip the temporary storage? eg. `awallet://share_content?u=example.com` (with % encoding)

2020-11-13 06:06 UTC, hboon commented on AlphaWalletShare/ShareViewController.swift
> +                self.showOpenURL { result in
Can we open the app right away instead of showing an actionsheet? Looks like it'll work if we do a `DispatchQueue.main.async(after:completion:)`?

2020-11-13 06:06 UTC, hboon commented on AlphaWallet/Share/ShareAction.swift
> +    case content = "share_content"
Can you rename most of the references to "share" to "openIn"? Eg. `ShareAction` and "share_content"? A bit more intention revealing.

2020-11-16 08:46 UTC, vladyslav-iosdev commented
@hboon can u review this PR?

2020-11-16 14:22 UTC, hboon requested changes
When I launch the extension from Safari, it switches to AlphaWallet, but when I go back to Safari, Safari doesn't respond anymore.

Doing this seems to help on the simulator.

```
DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
    self.open(url: url)
    context.completeRequest(returningItems: nil)
}

```

Can you see if this helps on the device too, or if there's a better way?

2020-11-17 03:41 UTC, hboon approved these changes
Thanks!

2020-11-17 03:42 UTC, merged