Generate and display blockies for wallets #2294
AlphaWallet/alpha-wallet-ios pull request #2299
Opened 2020-11-20 15:00 UTC by vladyslav-iosdev

Closes 2294

2020-11-24 04:42 UTC, James-Sangalli commented
@vladyslav-iosdev missing in the change wallet page

2020-11-24 04:52 UTC, hboon requested changes

2020-11-24 04:52 UTC, hboon commented on AlphaWallet/Core/Helpers/BlockieGenerator.swift
> +    private static var cache: [String: BlockiesImage] = [:]
The key can be `AlphaWallet.Address`.

2020-11-24 04:52 UTC, hboon commented on AlphaWallet/Core/Helpers/BlockieGenerator.swift
> +            if let image = blockies.createImage() {
This takes about ~2s when I run it so it blocks while the app is launching. Can we make it run in the background?

2020-11-24 09:56 UTC, hboon requested changes
> missing in the change wallet page

@vladyslav-iosdev don't forget that one

2020-11-25 03:37 UTC, hboon approved these changes

2020-11-25 03:37 UTC, merged