Do not show "ENS" label in Actionsheet for transaction confirmation under Recipient if there is no ENS name resolved (yet) #2310
AlphaWallet/alpha-wallet-ios pull request #2314
Opened 2020-11-24 09:58 UTC by vladyslav-iosdev

Closes #2310

2020-11-25 03:17 UTC, hboon requested changes
If we add a delay to slow down the reverse resolution in `ENSReverseLookupCoordinator` and go proceed to try to send to 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 (which should resolves to `vitalik.eth` in a while), this screen is still shown for a while until the ENS name appears:

<img width='200' src='https://user-images.githubusercontent.com/56189/100178766-92de7700-2f0f-11eb-919c-e6d871cd165d.png'>

2020-11-25 03:17 UTC, hboon commented on AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
> +//                var children: [UIView] = []
Can you remove the commented out code in the commit?

2020-11-25 03:17 UTC, hboon commented on AlphaWallet/Transfer/ViewControllers/TransactionConfirmationViewController.swift
> +//                header.childrenStackView.addArrangedSubviews(children)
Same here

2020-11-25 08:37 UTC, vladyslav-iosdev commented
> If we add a delay to slow down the reverse resolution in ENSReverseLookupCoordinator and go proceed to try to send to 0xd8da6bf26964af9d7eed9e03e53415d37aa96045 (which should resolves to vitalik.eth in a while), this screen is still shown for a while until the ENS name appears:

oh, i didn't check this case, working on it.

2020-11-26 04:47 UTC, hboon commented
@vladyslav-iosdev looks good. Is it go to review and merge?

2020-11-30 08:58 UTC, hboon commented
@vladyslav-iosdev build error. Maybe the `children` var was deleted when rebasing?

2020-11-30 09:09 UTC, hboon approved these changes
Thanks!

2020-11-30 09:09 UTC, merged