Crash with large wallet #2341
AlphaWallet/alpha-wallet-ios pull request #2365
Opened 2020-12-07 15:21 UTC by vladyslav-iosdev

Closes #2341, Closes #2340

2020-12-08 03:50 UTC, hboon requested changes

2020-12-08 03:50 UTC, hboon commented on AlphaWallet/Transactions/Storage/TransactionsStorage.swift
> +                return realm.object(ofType: Transaction.self, forPrimaryKey: each.primaryKey) != nil
I think this should be == nil instead?

2020-12-08 03:50 UTC, hboon commented on AlphaWallet/Core/Initializers/MigrationInitializer.swift
> +        //NOTE: use [weak self] to avaid memory leak
Good catch! Can you help pull move into a separate PR?

2020-12-10 03:54 UTC, James-Sangalli approved these changes

2020-12-10 03:54 UTC, merged