Add send all funds button #2450
AlphaWallet/alpha-wallet-ios pull request #2457
Opened 2021-01-14 14:58 UTC by vladyslav-iosdev

Closes #2450

2021-01-20 06:19 UTC, hboon requested changes
I tried this:

1. In Wallet tab
2. Tap ETH for Ropsten
3. Tap "All Funds"
4. Tap Paste (address)
5. Tap Send
6. When it hits `if self.amount.allFunds {`, `allFunds` is false

2021-01-20 06:19 UTC, hboon commented on AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
> +                    let diff: BigInt? = viewModel.value - (configurator.currentConfiguration.gasPrice * configurator.currentConfiguration.gasLimit)
`diff` can be non-optional

2021-01-20 06:19 UTC, hboon commented on AlphaWallet/Transfer/ViewModels/TransactionConfirmationViewModel.swift
> +                    let diff: BigInt? = viewModel.value - (configurator.currentConfiguration.gasPrice * configurator.currentConfiguration.gasLimit)
Also `diff` isn't intention-revealing. (it's not a difference of values)

2021-01-20 06:19 UTC, hboon commented on AlphaWallet/Transfer/Coordinators/SendCoordinator.swift
> +    var allFunds: Bool = false
More idiomatic: `isAllFunds`

2021-01-22 03:38 UTC, hboon commented
@vladyslav-iosdev this good for review again?

2021-01-25 05:40 UTC, hboon requested changes
If I do this:

1. Tap send Ropsten ETH
2. Tap All Funds
3. Paste address
4. Tap Send
5. Tap Confirm
6. It displays the error "insufficient funds for gas * price + value"

After rebasing master, I added a commit to show what might be wrong. There's a comment in it:

```
xxx balance: 894161570414202023 sending: 893972570414202023
xxx balance: 894161570414202023 sending: 893972570414202023
xxx form transaction with value: 894161570414202023
xxx balance: 894161570414202023 sending: 894037679172441023
```

2021-01-28 03:31 UTC, hboon requested changes
- [ ] See this (the `Amount`) when sending ERC20:

<img width='200' src='https://user-images.githubusercontent.com/56189/106085950-23c60e80-615c-11eb-9590-b1087b3302d6.png'>

- [ ] If the ETH balance is zero (and possibly when balance less than gas), sending ETH will crash. Not sure if it happens while sending ERC20s

2021-01-28 10:06 UTC, vladyslav-iosdev commented
> * [ ]  See this (the `Amount`) when sending ERC20:
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/56189/106085950-23c60e80-615c-11eb-9590-b1087b3302d6.png">
> 
> * [ ]  If the ETH balance is zero (and possibly when balance less than gas), sending ETH will crash. Not sure if it happens while sending ERC20s

it happens here `func hash(transaction: UnsignedTransaction) throws -> Data {` because of force unwrap, updated code to avoid it.

2021-02-17 07:36 UTC, hboon commented
@vladyslav-iosdev remember to reassign me for review if PRs are ready :)

2021-02-18 03:24 UTC, hboon approved these changes

2021-02-18 03:24 UTC, merged