add AnalyticsService Wrapper #2562
AlphaWallet/alpha-wallet-ios pull request #2563
Opened 2021-02-25 13:18 UTC by vladyslav-iosdev

Closes  #2562

2021-02-25 13:59 UTC, hboon reviewed
@vladyslav-iosdev I missed the context for this. Could you summarise?

2021-02-25 14:03 UTC, vladyslav-iosdev commented
That is just abstraction layer for analytics, For future in case if we would like to add more analytic services)

2021-02-25 14:05 UTC, hboon commented
Great idea. Thanks :)

2021-02-26 03:16 UTC, hboon requested changes

2021-02-26 03:16 UTC, hboon commented on AlphaWallet/Analytics/Coordinators/AnalyticsService.swift
> +
Needs to delegate this to `mixpanelService` too.

2021-02-26 03:16 UTC, hboon commented on AlphaWallet/Analytics/Models/AnalyticsEventPropertyValue.swift
> +    var value: Any { get }
Can you try to replace the call to `convertParameterToSdkSpecificVersion(_:)` with `value`?

2021-03-01 04:52 UTC, hboon commented
Force pushed after rebase master

2021-03-01 04:53 UTC, hboon approved these changes

2021-03-01 04:53 UTC, merged