Wrong amount in Send actionsheet #2661
AlphaWallet/alpha-wallet-ios pull request #2666
Opened 2021-03-22 10:19 UTC by vladyslav-iosdev

Closes #2599, Closes  #2661

2021-03-23 04:32 UTC, hboon commented
So this PR would fix #2655 too?

2021-03-23 05:00 UTC, hboon commented on AlphaWallet/Settings/Types/Config.swift
>      static var locale: Locale {
I know you mentioned this in #https://github.com/AlphaWallet/alpha-wallet-ios/issues/2655#issuecomment-803947279, but I don't understand.

When do we use `Config.locale` and when do we use `Config.getLocale()`? In other words, why do we want `Config.locale` to return `Locale.current` when the user has overridden the language in in-app Settings > Advanced > Change Language?

2021-03-23 05:01 UTC, hboon requested changes
I see this when iOS region is Singapore+English and in-app setting is Polish, after app is restarted. Notice it shows "0,1" in the amount textfield, but "0.1" in the actionsheet.

<img width="463" alt="Screenshot 2021-03-23 at 1 00 22 PM" src="https://user-images.githubusercontent.com/56189/112095620-c7212600-8bd7-11eb-9392-f3b7ebd4a780.png">

2021-03-24 03:42 UTC, hboon commented
@vladyslav-iosdev also see if https://github.com/AlphaWallet/alpha-wallet-ios/issues/2662#issuecomment-804614729 and the comments after that might be relevant?

2021-03-26 04:47 UTC, hboon commented
@all-contributors please add @vladyslav-iosdev for code

2021-03-26 08:01 UTC, vladyslav-iosdev commented
> #2655

yep, it should

2021-03-29 07:26 UTC, hboon commented
@vladyslav-iosdev it works on iOS 12.4 simulator, but I tried on an iPhone 11 Pro (device) with iOS 14.5 and changing the locale in-app to and after restarting the app, the keyboard and textfields still show "." as the decimal separator. Does it work for you?

2021-03-30 06:38 UTC, hboon commented
@vladyslav-iosdev going to merge this in and I'll create a separate PR to hide (and undo) the in-app language settings for now until we sort it out.

2021-03-30 06:40 UTC, hboon approved these changes

2021-03-30 06:40 UTC, merged