Resolve ref cycle for activities view #3011
AlphaWallet/alpha-wallet-ios pull request #3062
Opened 2021-08-12 10:31 UTC by vladyslav-iosdev

Closes #3011

2021-08-12 14:58 UTC, hboon reviewed
Will check. But seems like tests aren't building

2021-08-13 04:39 UTC, hboon requested changes
Can you describe what is causing the crash?

Also when switch wallets a few times in succession, it crashes with:

```
Process:               AlphaWallet [36427]
Path:                  /Users/USER/Library/Developer/CoreSimulator/Devices/054E4FD3-1742-4184-B69B-8E066E91501F/data/Containers/Bundle/Application/48A7DE9A-E3D1-4929-8CC8-2B72A390D61D/AlphaWallet.app/AlphaWallet
Identifier:            AlphaWallet
Version:               3.26 (398)
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [1603]
Responsible:           SimulatorTrampoline [1588]
User ID:               503

Date/Time:             2021-08-13 12:38:25.741 +0800
OS Version:            macOS 11.5 (20G71)
Report Version:        12
Bridge OS Version:     5.5 (18P4759a)
Anonymous UUID:        9F86FAA3-FF45-72BF-6464-2F956D3369F3

Sleep/Wake UUID:       EDD09906-CBCD-4B57-9824-B8D2F69C9A9C

Time Awake Since Boot: 39000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        56  Dispatch queue: com.EventSourceCoordinatorForActivities.updateQueue

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [36427]

Application Specific Information:
Swift/Integers.swift:3550: Fatal error: Not enough bits to represent the passed value
 
CoreSimulator 775 - Device: iPhone Xs 14.5 (054E4FD3-1742-4184-B69B-8E066E91501F) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone Xs

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00000001100802ba mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x000000011008062c mach_msg + 60
2   com.apple.CoreFoundation      	0x000000010dbe54f9 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x000000010dbdfb9c __CFRunLoopRun + 1296
4   com.apple.CoreFoundation      	0x000000010dbdf1a7 CFRunLoopRunSpecific + 567
5   com.apple.GraphicsServices    	0x0000000116645d85 GSEventRunModal + 139
6   com.apple.UIKitCore           	0x0000000117a114df -[UIApplication _run] + 912
7   com.apple.UIKitCore           	0x0000000117a1639c UIApplicationMain + 101
8   com.stormbird.alphawallet     	0x0000000102e92adb main + 75 (AppDelegate.swift:8)
9   libdyld.dylib                 	0x000000010fcbdbbd start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x0000000110138420 start_wqthread + 0

Thread 2:: JavaScriptCore bmalloc scavenger
0   libsystem_kernel.dylib        	0x0000000110082cde __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x000000011013ce49 _pthread_cond_wait + 1298
2   libc++.1.dylib                	0x0000000105010ef2 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   com.apple.JavaScriptCore      	0x000000011bfffea4 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 84
4   com.apple.JavaScriptCore      	0x000000011c004bfb bmalloc::Scavenger::threadRunLoop() + 251
5   com.apple.JavaScriptCore      	0x000000011c004579 bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*) + 9
6   com.apple.JavaScriptCore      	0x000000011c005e87 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*) + 39
7   libsystem_pthread.dylib       	0x000000011013c8fc _pthread_start + 224
8   libsystem_pthread.dylib       	0x0000000110138443 thread_start + 15

Thread 3:: WebThread
0   libsystem_kernel.dylib        	0x00000001100802ba mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x000000011008062c mach_msg + 60
2   com.apple.CoreFoundation      	0x000000010dbe54f9 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x000000010dbdfb9c __CFRunLoopRun + 1296
4   com.apple.CoreFoundation      	0x000000010dbdf1a7 CFRunLoopRunSpecific + 567
5   com.apple.WebCore             	0x000000011d1298e5 RunWebThread(void*) + 597
6   libsystem_pthread.dylib       	0x000000011013c8fc _pthread_start + 224
7   libsystem_pthread.dylib       	0x0000000110138443 thread_start + 15

Thread 4:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	0x00000001100802ba mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x000000011008062c mach_msg + 60
2   com.apple.CoreFoundation      	0x000000010dbe54f9 __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x000000010dbdfb9c __CFRunLoopRun + 1296
4   com.apple.CoreFoundation      	0x000000010dbdf1a7 CFRunLoopRunSpecific + 567
5   com.apple.Foundation          	0x0000000107c31204 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 209
6   com.apple.Foundation          	0x0000000107c31473 -[NSRunLoop(NSRunLoop) runUntilDate:] + 72
7   com.apple.UIKitCore           	0x0000000117ac9ccd -[UIEventFetcher threadMain] + 464
8   com.apple.Foundation          	0x0000000107c598a9 __NSThread__start__ + 1068
9   libsystem_pthread.dylib       	0x000000011013c8fc _pthread_start + 224
10  libsystem_pthread.dylib       	0x0000000110138443 thread_start + 15

Thread 5:: Realm notification listener
0   libsystem_kernel.dylib        	0x0000000110084c4a kevent + 10
1   org.cocoapods.Realm           	0x0000000108f8fcc7 realm::_impl::ExternalCommitHelper::listen() + 455 (external_commit_helper.cpp:216)
2   org.cocoapods.Realm           	0x0000000108f949e8 realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0::operator()() const + 24 (external_commit_helper.cpp:173)
3   org.cocoapods.Realm           	0x0000000108f9497d decltype(std::__1::forward<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(fp)()) std::__1::__invoke<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0&&) + 29 (type_traits:3747)
4   org.cocoapods.Realm           	0x0000000108f948e5 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>&, std::__1::__tuple_indices<>) + 37 (thread:280)
5   org.cocoapods.Realm           	0x0000000108f94136 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*) + 118 (thread:291)
6   libsystem_pthread.dylib       	0x000000011013c8fc _pthread_start + 224
7   libsystem_pthread.dylib       	0x0000000110138443 thread_start + 15

Thread 6:
0   libsystem_pthread.dylib       	0x0000000110138420 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x0000000110138420 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x0000000110138420 start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	0x0000000110138420 start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	0x0000000110138420 start_wqthread + 0

Thread 11:: Realm notification listener
0   libsystem_kernel.dylib        	0x0000000110084c4a kevent + 10
1   org.cocoapods.Realm           	0x0000000108f8fcc7 realm::_impl::ExternalCommitHelper::listen() + 455 (external_commit_helper.cpp:216)
2   org.cocoapods.Realm           	0x0000000108f949e8 realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0::operator [...]

2021-08-13 05:26 UTC, vladyslav-iosdev commented
> Can you describe what is causing the crash?

it doesn't resolve crash issue, this part is solving only memory leak that caused by `ActivitiesView`

2021-08-13 05:28 UTC, hboon commented
> > Can you describe what is causing the crash?
> 
> it doesn't resolve crash issue, this part is solving only memory leak that caused by `ActivitiesView`

Could you have linked to the wrong issue? :)

2021-08-13 05:30 UTC, vladyslav-iosdev commented
> > > Can you describe what is causing the crash?
> > 
> > 
> > it doesn't resolve crash issue, this part is solving only memory leak that caused by `ActivitiesView`
> 
> Could you have linked to the wrong issue? :)

hah no ,) i while trying to find crash cause, i found it, decided that this could be as part of this PR.

2021-08-13 05:33 UTC, hboon commented
Ok, fair enough. Is this ready for merging (after fixing the tests) as it is?

2021-08-13 05:38 UTC, vladyslav-iosdev commented
> Ok, fair enough. Is this ready for merging (after fixing the tests) as it is?

let me to fix tests first.

2021-08-16 08:20 UTC, hboon approved these changes

2021-08-16 09:17 UTC, merged