Fixed closing animation
AlphaWallet/alpha-wallet-ios pull request #3501
Opened 2021-12-03 06:34 UTC by eviltofu

Fixes #3493

The ModalViewController required it's own dismissal function instead of the standard one.

2021-12-03 07:56 UTC, hboon requested changes
Thanks. But can you modify the PR title and commit message to be specific?

2021-12-08 00:13 UTC, eviltofu commented
> Thanks. But can you modify the PR title and commit message to be specific?

@hboon How do I resolve this conflict?

2021-12-08 02:19 UTC, hboon commented
> @hboon How do I resolve this conflict?

Do you mean the conflict mentioned at the bottom of this GitHub PR page?

> This branch has conflicts that must be resolved

This means that the files that were modified in this PR has changed since in the `master` branch and git can't figure out how to merge them automatically (git is conservative here).

Do resolve it, on your local machine, do this:

1. git checkout eviltofu:Fix_ModalViewController_Animation #on the branch
2. git fetch <remote> master:master #Gets the latest `master` from `<remote>` and merges it into your local `master`
3. git rebase master #Modifies current branch i.e. `eviltofu:Fix_ModalViewController_Animation` so that the changes are based on top of `master`
4. There's probably conflicts, fix them (look for "<<<<") by editing files, making sure they look like how you want them to
5. git add .
6. DO NOT do `git commit`
7. git rebase --continue
8. Repeat 5-7 until it says it's done. There will be 1 commit (the one introduced by this PR, but with a new hash) above `master` in the output of `git log`

Replace `<remote>` with the remote name which has the latest master. Maybe `upstream` or `origin`?

2021-12-08 23:34 UTC, eviltofu commented
@hboon Needs review

2021-12-09 03:38 UTC, merged