Remove Eureka pod if it is only used for validation and not UI #3614
AlphaWallet/alpha-wallet-ios pull request #3756
Opened 2022-01-20 10:54 UTC by oa-s

Closes #3614

2022-01-20 10:59 UTC, eviltofu commented
@oa-s Can you add tests for all the rules?

2022-01-21 05:02 UTC, eviltofu commented
Ok so I just remembered that I implemented another version of PasswordTextField with some validation rules in ExportJSONKeyStore. @hboon Should we just use one?

2022-01-21 05:26 UTC, hboon commented
@eviltofu do you mean validation rules? Sure. If it's easy, either one of you fix it, otherwise, fix it after the PR, that's fine too.

2022-01-21 05:36 UTC, eviltofu commented
> @eviltofu do you mean validation rules? Sure. If it's easy, either one of you fix it, otherwise, fix it after the PR, that's fine too.

We'll fix after the PR.

2022-01-21 06:19 UTC, eviltofu commented
@oa-s Can you provide some instructions on how I can test this?

2022-01-21 07:23 UTC, oa-s commented
> @oa-s Can you provide some instructions on how I can test this?

try to make a wallet backup, it should lead you to open `EnterPasswordCoordinator`

2022-01-21 07:57 UTC, oa-s commented
> PasswordTextField

yep, its yours impl, just moved to separate class. it also needs to replace the other parts where is using `PasswordTextField`, maybe in another PR.

2022-01-24 01:16 UTC, eviltofu commented
> > @oa-s Can you provide some instructions on how I can test this?
> 
> try to make a wallet backup, it should lead you to open `EnterPasswordCoordinator`

Can you be more specific? I tried backing up via `Settings > Back up this Wallet` and it did not lead me to the Password Coordinator.

2022-01-24 06:31 UTC, hboon commented
@eviltofu  In case this saves you some time:

Import this private key [^1] 0xf4494504cd9fea2ce537bb3ffaf698ba6a9bd98172396d20bf24c9690560e14a and try to backup. It should be for the wallet address: 0xcfC55B007103BC5de32583A065B87b71a59Da074. It's an empty wallet.

Alternatively for HD-based wallet, Go to Advanced > Backup (Though this seem to be missing, can you check if it's a bug that it's missing. It's the one you added a few weeks ago)

[^1]: 2 types of wallets. HD/Seed-based wallets and "raw" private keys. This is the second type.

2022-01-24 06:34 UTC, eviltofu commented
> @eviltofu In case this saves you some time:
> 
> Import this private key [1](#user-content-fn-1-02ec13608f34998d5cc39ceec746e6d5) 0xf4494504cd9fea2ce537bb3ffaf698ba6a9bd98172396d20bf24c9690560e14a and try to backup. It should be for the wallet address: 0xcfC55B007103BC5de32583A065B87b71a59Da074. It's an empty wallet.
> 
> Alternatively for HD-based wallet, Go to Advanced > Backup (Though this seem to be missing, can you check if it's a bug that it's missing. It's the one you added a few weeks ago)
> 
> ## Footnotes
> 1. 2 types of wallets. HD/Seed-based wallets and "raw" private keys. This is the second type. [↩](#user-content-fnref-1-02ec13608f34998d5cc39ceec746e6d5)

The Settings > Advanced > ExportJSONKeyStore? That would not test the above code. After this PR is done I will fix the missing option. Seems like some other things are also missing. @hboon

2022-01-24 06:38 UTC, hboon commented
> The Settings > Advanced > ExportJSONKeyStore? 

Yes, something like that.

2022-01-25 02:33 UTC, eviltofu commented
The default for the password TextField should be to show the hidden text '****' instead of clear text. @oa-s

2022-01-25 07:39 UTC, eviltofu requested changes
Change `String(format: "%.5f", Float(String(ethCost))!)` to use a `NumberFormatter`

2022-01-25 07:39 UTC, eviltofu commented on AlphaWallet/InCoordinator.swift
>          tabBarController.tabBar.isTranslucent = false
I will file an issue to remove TabBarController. No other code uses it and it's name is too close to UITabBarController which can cause confusion. @hboon @oa-s

2022-01-25 08:13 UTC, oa-s commented on AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
> +        let ethCostRoundedTo5dp = String(format: "%.5f", Float(String(ethCost))!)
It comes from `Eureka` pod, there was batch of extensions for types like: Int, Fload and some other for creating instances  from `String` value. I just follwed their implementation and updated the code base with pretty the same as was there.

2022-01-25 08:22 UTC, oa-s commented on AlphaWallet/Core/Views/PasswordTextField.swift
> +    }
@eviltofu could this be a bit explained? not clear

2022-01-25 08:23 UTC, oa-s commented on AlphaWallet/Core/Views/PasswordTextField.swift
> +        isSecureTextEntry = true
@eviltofu we set `isSecureTextEntry ` here

2022-01-25 08:30 UTC, eviltofu commented on AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
> +        let ethCostRoundedTo5dp = String(format: "%.5f", Float(String(ethCost))!)
Ok, I'll file a new issue.

2022-01-25 08:34 UTC, eviltofu commented on AlphaWallet/Core/Views/PasswordTextField.swift
> +    }
I'm should have clicked one more line up. Ignore this since you already put this in the code.

2022-01-25 08:40 UTC, oa-s commented on AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
> +        let ethCostRoundedTo5dp = String(format: "%.5f", Float(String(ethCost))!)
emm, still not clear for me, but here what i want to convey

before pr, there was something like `let ethCostRoundedTo5dp = String(format: "%.5f", Float(string: String(ethCost))!)`
the pod contained extension
`extension Float {
    convenient init(string: String) {
        self.init(string)
    }
}`
so in the PR we just use the builded implementation of `.init` method
i updated all places where it was using init method of Eureka pod for Float, Int types

2022-01-25 08:46 UTC, oa-s commented on AlphaWallet/Transactions/Coordinators/TokensCardCoordinator.swift
> +        let ethCostRoundedTo5dp = String(format: "%.5f", Float(String(ethCost))!)
@eviltofu sent you an invitation to my repo to make an ability to edit code

2022-01-26 03:34 UTC, merged