Rewriting URLs for images hosted on Google to higher resolution versions #3894
AlphaWallet/alpha-wallet-ios pull request #3909
Opened 2022-02-14 12:51 UTC by oa-s

Closes #3894

2022-02-14 14:52 UTC, hboon commented
@oa-s will take a look. But some quick feedback:

* Copyright says 2020
* The README mentions your gmail address (if you are ok with it)

2022-02-15 04:04 UTC, hboon requested changes
Looks great so far! Thanks!

2022-02-15 04:04 UTC, hboon commented on modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift
> +    case googleContentRewritten(URL)
Are we rewriting the URL for Google hosted images for all cases? Should we add a case or somehow be able to choose when to use the original. Eg. we only want to use the rewritten, bigger version when in Wallet > Collectibles, and Info, and in the screen showing a single token ID, but not in screens like the little icons in Wallet tab or Activity Tab. 

Concerned with memory usage and speed.

2022-02-15 06:18 UTC, oa-s commented on modules/AlphaWalletCore/AlphaWalletCore/WebImageURL.swift
> +    public var url: URL {
made it as public as we need back convertation to `URL`

2022-02-15 09:27 UTC, oa-s commented
@hboon Its ready.

2022-02-15 10:24 UTC, hboon commented
Merge when you are ready

2022-02-16 11:06 UTC, merged