Added code to read tokens.json and sort the tokens into defi, goverance, assets, collectibles
AlphaWallet/alpha-wallet-ios pull request #4304
Opened 2022-04-12 11:15 UTC by eviltofu

Closes #3581
![Simulator Screen Shot - iPhone 11 - 2022-04-12 at 19 17 52 copy](https://user-images.githubusercontent.com/1050309/162948881-11da3a2b-e69a-458d-b832-bedabceddb8d.png)
Old

![Simulator Screen Shot - iPhone 11 - 2022-04-12 at 19 16 51 copy](https://user-images.githubusercontent.com/1050309/162948873-8a10eff2-fe73-4c0f-be7a-cebc1b004ee8.png)
New

2022-04-12 11:15 UTC, eviltofu commented
I don't know if there tokens.json file needs to be updated. I can't tell if the defi / governance tabs are properly working.

2022-04-13 07:07 UTC, hboon requested changes
> I don't know if the tokens.json file needs to be updated.

It's the correct version.

> I can't tell if the defi / governance tabs are properly working. From the images above, you can see that the assets tabs are both different.

After the changes, it's likely that DeFi and Governance that will be empty or have only a few tokens. You can manually add a toke you know belong to those 2 tabs by:

1. Wallet tab
2. Tap …
3. Add/Hide Tokens
4. Paste and follow through to add (on the right chain)

2022-04-14 00:09 UTC, eviltofu commented
I'm looking at a coinbase [article](https://www.coindesk.com/learn/what-are-defi-tokens/) and it says Link, Dai and Luna are DeFi but I've added those and the DeFi tab is still blank. @hboon

2022-04-14 00:13 UTC, eviltofu commented
> > I don't know if the tokens.json file needs to be updated.
> 
> It's the correct version.
> 

I've checked the git log. It's not been modified since I added it?

2022-04-14 01:01 UTC, hboon commented
Will check when I’m back but check against tokens.json that you embed, not against an external article. If you check against the article, update tokens.json instead.

2022-04-14 03:27 UTC, hboon commented
> I've checked the git log. It's not been modified since I added it?

No, the copy you used hasn't been committed yet, so it's the lastest we have.

2022-04-14 03:30 UTC, hboon commented
> Will check when I’m back but check against tokens.json that you embed, not against an external article. If you check against the article, update tokens.json instead.

@eviltofu So if you add the contract `0x21bfbda47a0b4b5b1248c767ee49f7caa9b23697` (chaindId = 1), the first entry in `tokens.json` you'll see it appear under the Governance tab. This test will only verify if the tokens.json is parsing correctly of course. Unless you are referring to testing something else?

2022-04-14 03:35 UTC, hboon approved these changes
Can merge after rebasing.

2022-04-14 03:35 UTC, hboon commented on AlphaWallet.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "pins" : [
Can you rebase master (or one of the earlier ones which still builds like `31d3fe25affce53c9ce42464b653b9bd97b87537`)? It'll get rid of this in the PR.

2022-04-14 04:19 UTC, merged

2022-04-18 03:45 UTC, hboon commented
Closes #3546