#4507 add select network screen after you create import a new wallet
AlphaWallet/alpha-wallet-ios pull request #4587
Opened 2022-05-12 11:55 UTC by eviltofu

Closes #4507.

##### Create Wallet Test:
1. Delete the app from your device.
2. Run.
3. Select "Create wallet" (screen 7).
4. Expect InitialNetworkSelectionViewController (screen 1) to show up.
5. Select one or more networks in main net.
6. Press continue button.
7. Expect TokensViewController (screen 6) to show up.

##### Import Wallet Test:
1. Delete the app from your device.
2. Run.
3. Select "I already have a wallet" (screen 7).
4. Select "Import existing wallet" (screen 8).
5. Enter wallet data.
6. Expect InitialNetworkSelectionViewController (screen 1) to show up.
7. Select one or more networks in mainnets.
8. Press continue button.
9. Expect TokensViewController (screen 6) to show up. 

#### Watch Wallet Test:
1. Delete the app from your device.
2. Run.
3. Select "I already have a wallet" (screen 7).
4. Select "Track wallet address" (screen 8).
5. Enter wallet address.
6. Expect TokensViewController (screen 6) to show up. 

#### Testnet Test:
1. Delete the app from your device.
2. Run.
3. Select "Create wallet" (screen 7).
4. Expect to see InitialNetworkSelectionViewController (screen 1).
5. Click on the Mainnet toggle switch to turn off mainnets.
6. Expect Overlay to appear (screen 3).
7. Press "Got it, enable testnets" button.
8. Expect Testnets screen (screen 4).
9. Click on the Testnet toggle switch to turn off testnets.
10. Expect to see InitialNetworkSelectionViewController (screen 1).

#### Filter Test:
1. Delete the app from your device.
2. Run.
3. Select "Create wallet" (screen 7).
4. Expect to see InitialNetworkSelectionViewController (screen 1).
5. Select the searchBar and type some letters.
6. Expect to see searchBar filtering (screen 2).

#### Continue button Test:
1. Delete the app from your device.
2. Run.
3. Select "Create wallet" (screen 7).
4. Expect to see InitialNetworkSelectionViewController (screen 1).
5. Deselect all networks.
6. Expect to see Continue button disabled (screen 5)

| Screen # | 
| ----- |
| ![Screen 1](https://user-images.githubusercontent.com/1050309/168063954-5a1e27f4-d692-4558-be46-6f74023ec2ed.png)<BR>Screen 1<BR>InitialNetworkSelectionViewController |
| ![2](https://user-images.githubusercontent.com/1050309/168064528-874d483a-0ac4-484c-a8f6-fb143d171d29.png)<BR>Screen 2<BR>SearchBar filtering |
| ![3](https://user-images.githubusercontent.com/1050309/168064726-1033fb71-7e2d-4cdb-bade-98aa29a94c46.png)<BR>Screen 3<BR>Testnets Overlay |
| ![4](https://user-images.githubusercontent.com/1050309/168065393-199db8e3-0a73-4d0d-82cb-2e803acb9a88.png)<BR>Screen 4<BR>Testnets |
| ![5](https://user-images.githubusercontent.com/1050309/168065699-b71e2444-eb71-4330-a445-695cefed0222.png)<BR>Screen 5<BR>Continue button disabled when no networks are selected |
| ![6](https://user-images.githubusercontent.com/1050309/168066150-61c14f19-6876-4a5b-b003-ff4cbb6616a9.png)<BR>Screen 6<BR>TokensViewController |
| ![7](https://user-images.githubusercontent.com/1050309/168066696-99b82bd3-55a0-48d2-9bcd-cd7e9a4b28f7.png)<BR>Screen 7<BR>Initial Wallet Creation |
|
![8](https://user-images.githubusercontent.com/1050309/168067165-3d8feed1-629f-487e-8fe4-2b3d16b097e0.png)<BR>Screen 8<BR>Import/Track Wallet Options |

2022-05-13 01:39 UTC, eviltofu commented
Ack! I need to implement the empty screen when the search filter turns up nothing.

2022-05-13 03:32 UTC, hboon commented
Can just skip it and do it in another PR. If reasonable, always merge a smaller PR.

2022-05-13 03:47 UTC, hboon requested changes
- [x] Switching to testnets should have some defaults like in Settings > Select Active Networks.

- [x] Switching to testnets and selecting some still only enables the default mainnets:

    1. Delete app
    2. Build and install
    3. Create wallet
    4. Switching to testnets
    5. Tap to enable Ropsten
    6. Continue

    Expected:

    Wallet tab shows Ropsten

    Observed:

    Wallet tab shows Ethereum, Gnosis and Polygon enabled (instead of Ropsten testnet)

    Settings > Select Active Networks shows these mainnets too.

2022-05-13 04:07 UTC, hboon requested changes

2022-05-13 04:07 UTC, hboon commented on AlphaWallet/Wallet/ViewModels/InitialNetworkSelectionViewModel.swift
> +    private func configureViewModel() {
Can just call it `configure()`

2022-05-17 02:11 UTC, eviltofu commented
The current master f8a81891fe88186401f131890fefc560a455b597 has the following behaviour:

If I make changes in the main nets, then return to the main screen, I get the main screen. I cannot select no active networks. Selecting no active networks and returning to the main screen does not give an error message; the app simply does nothing. The app should inform the user.

![Simulator Screen Recording - iPhone 11 - 2022-05-17 at 10 09 09](https://user-images.githubusercontent.com/1050309/168714008-acc40654-3e4d-4d08-b507-7eb2cd0f62c3.gif)

@hboon

2022-05-17 02:16 UTC, eviltofu commented
I'm going to add the following behaviour:

1) If main nets or tests nets are selected and there are no active selected networks, a default set of selected networks will be presented.
2) When no networks are selected in the current screen (main net or test net), the user cannot hit the continue button.
3) The current selected screen (main net or test net) will have their selected networks loaded. The selected networks in the other screen (test net or main net) will be ignored.

2022-05-20 04:54 UTC, hboon commented
> If I make changes in the main nets, then return to the main screen, I get the main screen. Selecting no active networks and returning to the main screen does not give an error message; the app simply does nothing. The app should inform the user.

I'm not sure if you decided on something different in the earlier comment, if so ignore this:

I think it's good to just go back and do nothing if the user de-selects everything. It's a less hassle than the user trying to remember what they want to select, and less disruptive than a popup, but not too important.

2022-05-20 04:57 UTC, hboon commented
> 1. If main nets or tests nets are selected and there are no active selected networks, a default set of selected networks will be presented.

This is right after creating a wallet right? Sounds OK.

> 2. When no networks are selected in the current screen (main net or test net), the user cannot hit the continue button.

OK, but this contradicts (1) above

> 3. The current selected screen (main net or test net) will have their selected networks loaded. The selected networks in the other screen (test net or main net) will be ignored when the continue button is pressed.

Not sure what this means.

> Should the user not be allowed to deselect the last selected network?

They should be allowed to with the expectation that they go and select another network. Otherwise it'd be annoying and confusing.

2022-05-20 05:07 UTC, hboon approved these changes
Looks good.

2022-05-24 04:45 UTC, eviltofu commented
> > 1. If main nets or tests nets are selected and there are no active selected networks, a default set of selected networks will be presented.
> 
> This is right after creating a wallet right? Sounds OK.
> 
> > 2. When no networks are selected in the current screen (main net or test net), the user cannot hit the continue button.
> 
> OK, but this contradicts (1) above

The user can deselect networks.
> 
> > 3. The current selected screen (main net or test net) will have their selected networks loaded. The selected networks in the other screen (test net or main net) will be ignored when the continue button is pressed.
> 
> Not sure what this means.

If you are in test net, only test nets will be added. If you are in main nets, only main nets will be added. 

> 
> > Should the user not be allowed to deselect the last selected network?
> 
> They should be allowed to with the expectation that they go and select another network. Otherwise it'd be annoying and confusing.

2022-05-24 04:46 UTC, merged

2022-12-22 07:53 UTC, hboon commented
> I will squish and merge once approved.

Eek. That didn't happen.