Add tracking large nft asset json strings, generating errors for crashlytics #4565
AlphaWallet/alpha-wallet-ios pull request #4885
Opened 2022-06-21 12:44 UTC by oa-s

Closes #4565

2022-06-21 13:11 UTC, hboon commented
Haven’t check it yet, but if you are loading the JSON, can you log the lengthy instead of the content? It’s huge :)

2022-06-22 04:04 UTC, hboon requested changes
Can you make `LogLargeNftJsonFilesTests.swift` smaller? A 2MB file is hard on git :) It can be just a tiny string as long as we can trigger the test somehow?

2022-06-22 04:04 UTC, hboon commented on AlphaWallet/Core/Helpers/FirebaseReportService.swift
> +                let rawAssets = rawAssets.compactMap { asset in asset.json.data(using: .utf8).flatMap { return (data: $0, value: asset) } }
We can avoid unnecessary computation (String -> Data) be it big or small.

Maybe just `rawAssets.map { $0.json.count }`?

And change the threshold, if necessary to compensate?

2022-06-22 06:13 UTC, oa-s commented
> Can you make LogLargeNftJsonFilesTests.swift smaller? A 2MB file is hard on git :) It can be just a tiny string as long as we can trigger the test somehow?

yes, sure.

2022-06-24 13:20 UTC, merged