Fixed dark mode in select active networks test net screen
AlphaWallet/alpha-wallet-ios pull request #5671
Opened 2022-10-25 08:53 UTC by eviltofu

Tap `Settings > Select Active Networks`, then toggle the `Testnet` switch to on. Tap the `enable testate` button on the pop up dialog.

Before | After
-|-
![before-1](https://user-images.githubusercontent.com/1050309/197729092-d29e7387-1959-4163-9e0c-d7421aefb61f.png)|![after-1](https://user-images.githubusercontent.com/1050309/197729075-0da430ae-c841-4a54-a81b-df411dcf0ed4.png)

2022-10-25 13:18 UTC, hboon commented
Can you not include this commit in PRs again? https://github.com/AlphaWallet/alpha-wallet-ios/pull/5671/commits/037ddf1c203390f0da162b3760ded342c1c35253

2022-10-25 13:18 UTC, hboon requested changes
Can you not include this commit in PRs again? https://github.com/AlphaWallet/alpha-wallet-ios/pull/5671/commits/037ddf1c203390f0da162b3760ded342c1c35253

2022-10-28 13:00 UTC, oa-s approved these changes

2022-10-28 13:02 UTC, oa-s commented
merge after rebase when you ready

2022-10-31 04:34 UTC, merged