Replace DappError with JsonRpcError #6456
AlphaWallet/alpha-wallet-ios pull request #6457
Opened 2023-03-03 17:36 UTC by oa-s

Closes #6456

2023-03-05 01:49 UTC, hboon approved these changes
Does this require this to be included? — https://github.com/AlphaWallet/AlphaWallet-web3-provider/issues/38

2023-03-05 01:50 UTC, hboon commented
(of course it does, you mentioned it in the issue. Hah!). So marking as `WIP. Don't Merge` first.

2023-03-05 02:02 UTC, hboon requested changes
Just in case. Some questions

2023-03-05 02:07 UTC, hboon reviewed
Do we need to look at https://github.com/AlphaWallet/alpha-wallet-ios/pull/6457 and https://github.com/AlphaWallet/AlphaWallet-web3-provider/pull/39 together and merge together? (then https://github.com/AlphaWallet/alpha-wallet-ios/pull/6457 needs to be updated to use the updated JS after https://github.com/AlphaWallet/AlphaWallet-web3-provider/pull/39  is merged)

2023-03-05 02:07 UTC, hboon commented on AlphaWallet/Browser/ViewControllers/BrowserViewController.swift
> +    func notifyFinish(callbackID: Int, value: Swift.Result<DappCallback, JsonRpcError>) {
A few lines below this:

```
return "executeCallback(\(callbackID), \"\(error.message)\", null)"
```

Does it need to be changed? If it's not, the new code `-32603` is not passed along right?

2023-03-05 08:32 UTC, oa-s commented
> Does this require this to be included? — [AlphaWallet/AlphaWallet-web3-provider#38](https://github.com/AlphaWallet/AlphaWallet-web3-provider/issues/38)

not now, after https://github.com/AlphaWallet/AlphaWallet-web3-provider/issues/38 we can update code to apply error `code`

2023-03-06 02:05 UTC, hboon approved these changes

2023-03-06 02:05 UTC, merged