Sorted session in SwapOptionsConfigurator to show mainnets first and testnets last.
AlphaWallet/alpha-wallet-ios pull request #6667
Opened 2023-04-10 08:52 UTC by eviltofu

Closes #6543 
Before | After
-|-
![before](https://user-images.githubusercontent.com/1050309/230865755-d8ccff3b-c853-4153-a7a8-3138def2d0ad.png)|![after](https://user-images.githubusercontent.com/1050309/230865764-235a2d4b-a05c-49bd-bb3f-30c3434085e1.png)

2023-04-10 10:52 UTC, hboon requested changes
Can you write it like this instead?

```
sessions = functional.sortSessionsWithMainnetsFirst(sessions: sessions)
invalidateSessionsWhenSupportedTokensChanged()
fetchSupportedTokensForSelectedServer()
resetToTokenForNonSupportedSwapPair()
```

Doesn't flow as well as your original version, but goes towards gradually reduce state-modifying code (mentioned in #6606)

2023-04-11 01:54 UTC, eviltofu commented
Review @hboon

2023-04-11 03:11 UTC, hboon commented on modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/SwapOptionsConfigurator.swift
> +public extension SwapOptionsConfigurator {
Shouldn't be `public`

2023-04-11 03:11 UTC, hboon commented on modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/SwapOptionsConfigurator.swift
> +public extension SwapOptionsConfigurator.functional {
Shouldn't be `public`

2023-04-11 03:11 UTC, hboon approved these changes

2023-04-11 03:37 UTC, eviltofu commented on modules/AlphaWalletFoundation/AlphaWalletFoundation/SwapToken/NativeSwap/Helpers/SwapOptionsConfigurator.swift
> +public extension SwapOptionsConfigurator.functional {
Removed

2023-04-11 04:13 UTC, merged