Fixed testReadingExistingNonJsonFile by reading an actual non-json file
AlphaWallet/alpha-wallet-ios pull request #6739
Opened 2023-04-25 23:54 UTC by eviltofu

Changed the input to read an actual non-json file.

2023-04-26 02:09 UTC, hboon requested changes

2023-04-26 02:09 UTC, hboon commented on AlphaWalletTests/Tokens/TokenGroupIdentifierTest.swift
> +        let url = Bundle.main.url(forResource: "chains", withExtension: "zip")
`R.file.chainsZip()` then? More "type-safe"

2023-04-27 00:51 UTC, eviltofu commented on AlphaWalletTests/Tokens/TokenGroupIdentifierTest.swift
> +        let url = Bundle.main.url(forResource: "chains", withExtension: "zip")
Replaced.

2023-04-27 01:14 UTC, hboon approved these changes

2023-04-27 01:14 UTC, merged